### ISSUE TITLE
region in safezone/warzone

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#10]
Hello,

Is it possible to add possibility when we create a region in safezone or warzone, this one take priority for flags ?

thank a lot 
PS: If you want, i can try to help you for developping this plugin (i already do a pull request)

**Comment by Aquerr** [comment]
Hmmm... A region? Did you mean a region from a plugin like **FoxGuard** or **UniverseGuard**?

I am aware that you will need to use only theirs functions and skip using claiming from Eagle Factions.

I can try to do an integration in the future but tell me first if it is it that you were thinking about 😄

**Comment by yodaa59** [comment]
Yes !

If i using only their functions, the players can claim the region because it is not a claimed chunk !

And i would like to add faction's houses in the safe zone for players can build in this and only in this region ! (and the region dont have the size of a chunk)

**Comment by yodaa59** [comment]
I think, the better if it's a plugin like FoxGuard or UniverseGuard are activated on server, when an action is performed in Safezone or Warzone, the plugin need to check if a region are set, where the player are, or not.

If region are set, it use the flags for region (or don't protect) and not the flag for factions !

**Comment by Aquerr** [comment]
Hmmm... there can be much more work in this than I thought.

**Eagle Factions** and **UniverseGuard/FoxGuard** are taking hand of chunks/regions individually. It will be hard to make a connection between these plugins... but it is not impossible I think.

A temporary solution to this may be:
* Claim everychunk as SafeZone
* Give players permission to build in SafeZone
* Create a region using FoxGuard/UniverseGuard
* Set flags in this region so it will work like you want

I am not sure if it can be a good solution but you can try to experiment with this.

**Comment by Aquerr** [comment]
As because I am cleaning all issues now and I has been some time since this issue got opened, I will be closing it.
Feel free to reopen or make a new one if you see such need.
