### ISSUE TITLE
I CANT TOUCH WORLD-NO PERM/WILDERNESS

### ISSUE THREAD

**Issue by varnithian97** [Aquerr/EagleFactions#100]
## Environment

* **Sponge Version:** <7.1>

* **Plugin Version:** <Your Plugin Version>

## What happens?

<Try to remove block, or do anything.>

## Result? 

<block should be removed but says that "i cannot break blocks in wilderness.>

## More information

<However there is no wilderness faction to join, so im curious how to fix this. .>

**Comment by Aquerr** [comment]
**Wilderness is not a faction thus you can't find it or join it.** Every part of the world that is not claimed by factions is counted as wilderness. Or in other words, wilderness is normal Minecraft world that is not affected by factions.

**Breaking blocks in wilderness is always permitted.** Strange that you are experiencing such issue as no one has reported it before.
Please paste here **the exact message** you are getting when you try to break a block in wilderness. 

Also, you can try breaking a block in factions **admin mode** --> **/f admin**. See if that helps, if it does not then something is really broken.
You can also get a little bit **more information** about the breaking if you activate **debug mode** --> **/f debug**.

**Comment by varnithian97** [comment]
Thanks for the quick reply! So I turned on debug mode, tried to place block and this is what i got.

Current permissions


eaglefactions.player
eaglefactions.admin
eaglefactions
/f admin on
![mcdebugfactions](https://user-images.githubusercontent.com/59478226/71782162-17956f00-2fa5-11ea-9a13-faccf777fcf6.png)

--



--

**Comment by Aquerr** [comment]
This does not look like a message from Eagle Factions. Are you using any other **protection** plugins?

**Comment by varnithian97** [comment]
weird, Im with the train of thought you are on though, im using griefprevention as the only other protection one, worldedit for quick building, and luckperms/nucleus for core commands.

I moved from region to region and this is what i got too, does it normally state faction as wilderness?

**Comment by varnithian97** [comment]
![asd](https://user-images.githubusercontent.com/59478226/71782221-d5b8f880-2fa5-11ea-9ba7-0452d0d8111d.png)

**Comment by Aquerr** [comment]
"**You have entered faction Wilderness**" comes from Eagle Factions. It is a message that you are getting when moving between chunks. However "You cannot place blocks in Wilderness" does **not** come from Eagle Factions. Eagle Factions prints "**You don't have access to do this!**" if you don't have permissions for placing/destroying a block. I am guessing it may be **GriefPrevention** that is stopping you from placing/destroying blocks.

**Comment by varnithian97** [comment]
Yeah so i uninstalled your plugin to make sure and I still get the error, think im going to just remove grief prevention but i have a questionfirst, in factions im thinking to set the world to primarily warzone and make warzone edit permissions for default users. But can people claim from the warzone space? or do i have to plan out a warzone and leave the rest open for them to claim?

**Comment by Aquerr** [comment]
Warzone cannot be claimed and there is no config for changing it.

The thing you can do is... mark a world as claimable world, claim chunks you want to have for warzone and then let the players claim any other chunks. Or have multiple worlds. One world for warzone and one where players can claim.

**Comment by Aquerr** [comment]
If this issue is solved then feel free to close it. :)

**Comment by varnithian97** [comment]
Apologies, for reference it was a broken string in griefprevention which corrupted the configs., had to do a clean reset and install now im back up and running fine. Appreaciate the help!

**Comment by Aquerr** [comment]
No problem! I am happy you solved it! 💪
