### ISSUE TITLE
Feature Request: Buy Claims

### ISSUE THREAD

**Issue by Kitsumi** [Aquerr/EagleFactions#101]
## Feature Request
Would it be possible to add a way to make claims by using currency instead of buying power?

**Comment by Aquerr** [comment]
It would be possible.

However, I am not sure if such feature should be included in standard version of Eagle Factions. Maybe it should be rather available as an add-on plugin that would connect itself to EF.

Furthermore, it is not a feature I would want to work on at this moment as it would require some changes in the code and some additional reflections around how this should work.

I will definitely have this in mind and I will add it to my TO DO list.

**Comment by Aquerr** [comment]
As because I am cleaning all issues now and I has been some time since this issue got opened, I will be closing it.
Feel free to reopen or make a new one if you see such need.

Also, this feature will be available in EF-s add-on https://github.com/Aquerr/EagleFactions-Economy
