### ISSUE TITLE
Can't change page

### ISSUE THREAD

**Issue by sTiKyt** [Aquerr/EagleFactions#112]
## Environment

* **Minecraft:** 1.12.2
* **SpongeAPI:** 7.2-fe189dcf
* **Sponge:** 1.12.2-7.2.0
* **SpongeForge:** 1.12.2-2838-7.2.0
* **Minecraft Forge:** 14.23.5.2847
* **JVM:** 1.8.0_242/64-bit (Private Build)
* **OS:** Linux (4.15.0-66-generic/amd64)

* **Plugin Version:** 0.14.1

## What happens?

When i write /factions or /f i can see one page of commands, but there's no way to change commands page. When i try to press highlighted ">>" nothing happens. Also there seems to be no chat command to switch page.

## Expected result
Working ">>" button or chat command to switch help pages
 
## More information

I'm using Nucleus

**Comment by Aquerr** [comment]
@sTiKyt Button for switching the page are working for me in the latest dev build so it is possible that something got broken in 0.14.1 and it is fixed now. Indeed there is not command for switching the page. I will try to add it so that it will be available in the next release.
