### ISSUE TITLE
Uppercase or lowercase

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#12]
Hello,

I have a probleme with commands ! 

When using commands, do not take into account capital letters!

It's possible to make fix for that ?

**Comment by Aquerr** [comment]
I don’t understand what you mean. 
Explain more so I can take a look at this.
Maybe an example?

**Comment by yodaa59** [comment]
For example : 
I make a faction with name : TestFac
When a player want to get info on it and type "/f i testfac" this one don't be done !
But when he type "/t i TestFac" it's good (with capital letters)

I think it's the same for all commands 

thanks :)

**Comment by Aquerr** [comment]
Oh, okay.

I remember that It doesn’t matter if letters are uppercase or lowercase when it comes to **/f create** but I may have forgotten about other commands 😝

I am gonna fix this!

**Comment by Aquerr** [comment]
This issue is fixed now!

It will be available in the next release!

I am closing this thread.
