### ISSUE TITLE
/f attack broken message

### ISSUE THREAD

**Issue by SMD404** [Aquerr/EagleFactions#120]
## Environment

* **Sponge Version:** 1.12.2-2838-7.2.1

* **Plugin Version:** 0.15.1

## What happens?

If I use the attack on faction /f attack, and enemy trying to grab back their lands, 
then he gets a broken message
![alt text](https://i.imgur.com/FflmZnJ.png)

**Comment by Aquerr** [comment]
Fixed in dev. 0.15.2 will contain this fix.

**Comment by Aquerr** [comment]
Fixed in 0.15.2
