### ISSUE TITLE
Сreating by items not working

### ISSUE THREAD

**Issue by SMD404** [Aquerr/EagleFactions#121]
## Environment

* **Sponge Version:** 1.12.2-2838-7.2.1

* **Plugin Version:** 0.15.1

## What happens?

Config: https://gist.github.com/SMD404/b43f70dd9447702fcbb7fd23271d0aae

When i use creating-by-items, doesn't add me to the faction, and i can't control my faction

create faction 
![alt text](https://i.imgur.com/2AKo3Xv.png) 
faction information
![alt text](https://i.imgur.com/WJLEkvX.png)

**Comment by Aquerr** [comment]
Fixed! Will be ready to use in 0.15.2.

**Comment by Aquerr** [comment]
Fixed in 0.15.2
