### ISSUE TITLE
Dynmap config - colors don't change

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#124]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.1.9

* **Plugin Version:** EagleFactions-0.15.1
## What happens?

I try to change the colors of the factions' and safezone's borders in Dynmap config section, save the changes, but the standard color remains on the Dynmap.
Ex.:
I try to change this:
    ### Customization (you can pick the colors on HEX color pciker)
    # Color of faction that isn't Safe or War zone
    faction-color=0x00FF00
To this:
    ### Customization (you can pick the colors on HEX color pciker)
    # Color of faction that isn't Safe or War zone
    faction-color=0xFF0000
But after the save the first color remains.

## Expected result

It should change the color of the borders to the new one.

## More information

I'm using the newest version of Dynmap (Dynmap-3.0.1-forge-1.12.2)

**Comment by Faelris** [comment]
Also, reloading the Dynmap causes the server to crash, saying smth about the scheduler update:
https://pastebin.com/kHFrpCpN

**Comment by Aquerr** [comment]
Fixed in 0.15.2
