### ISSUE TITLE
Select SafeZone/WarZone area with //wand

### ISSUE THREAD

**Issue by WareZ57** [Aquerr/EagleFactions#13]
Hey, is it possible to select WarZone / SafeZone with // wand?  because the autoclaim is not centered.

Or any idea for claim properly ?

   Thx

**Comment by Aquerr** [comment]
No, it is not possible.

You can only use **/claim** or **/autoclaim**. It will claim a chunk you are currently standing in. (16x16)

You will need to adjust your buildings to claims.

**Comment by WareZ57** [comment]
Hummm ok but would not it be possible to add this feature later ?

Thx you, you can close the thread if you want !

**Comment by Aquerr** [comment]
Maybe in the future but it would require to change the entrie claiming system from chunks to blocks.
