### ISSUE TITLE
dynmap faction claims update

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#131]
## Environment

* **Sponge Version:** 
spongeforge-1.12.2-2838-7.3.0
* **Plugin Version:** 
EagleFactions-1.12.2-v0.15.3
Dynmap-3.0.1-forge-1.12.2
## What happens?
Hi! 
It seems that faction chunk claims update weirdly on dynmap. I'm not sure if it's about dynmap or factions.
Firstly, when I do /f reload, claimed chunks for all factions disappear from the dynmap, and there's a continuous error in a console (scheduler): https://pastebin.com/a9S9Mzyz 
Familiar with error like here: https://github.com/Aquerr/EagleFactions/issues/124#issuecomment-644112518

Secondly, it seems the update of newly claimed chunks do not appear on dynmap after the event of claiming. Restarting the server helps, but I guess it's not like it's intended to work that way.

## Expected result

1. Reloading the plugin should also make claims properly appear on dynmap.
2. Newly claimed chunks should appear on dynmap as is, or with some delay.

**Comment by Aquerr** [comment]
Thanks for reporting the issue! I will look at it asap.

**Comment by Aquerr** [comment]
@Faelris Disappearing of factions from dynmap after preforming a reload is a normal thing. You don't need to worry about it. Eagle Factions is simply removing all markers from the Dynmap and tells Dynmap to recreate them. 

When it comes to your log, then yes... indeed there is something wrong in there.
However, I am having difficulties when trying to reproduce it in my dev-environment. I started the server, claimed some chunks, reloaded the plugin and everything is working fine.
 
Hmmm... Could you try the latest version of the plugin (which is 0.15.3.1)?

If it will not help then feel free to ping/mention me here.

**Comment by Faelris** [comment]
@Aquerr /f reload now works fine. After reloading all newly claimed chunks appeared on the map. I'm not quite sure about updating yet - I suppose these chunks should update on dynmap even without /f reload in some regular time interval? Or are they intended to update only after /f reload?

**Comment by Aquerr** [comment]
New claims should show up on dynmap automatically. An update occurs every 10 seconds.

**Comment by Ytoblo** [comment]
![image](https://user-images.githubusercontent.com/45790049/102707546-c9fd3980-42bd-11eb-943c-6ecd52d0271f.png)

**Comment by Ytoblo** [comment]
chunks of course appear after rebooting the server, but this is very inconvenient

**Comment by Aquerr** [comment]
Going to look at it again this week. @Ytoblo are you using the same version of EF, Sponge and Dynmap as OP?

**Comment by Ytoblo** [comment]
> Going to look at it again this week. @Ytoblo are you using the same version of EF, Sponge and Dynmap as OP?

im using:
spongeforge-1.12.2-2838-7.3.0
EagleFactions-1.12.2-v0.15.4
Dynmap-3.0.1-forge-1.12.2

**Comment by Ytoblo** [comment]
ok, i downloaded "426-SNAPSHOT" and test. I have identified the following problems:
Display of claim still not working (how much I waited, nothing appeared), BUT after reloading EagleFactions no more errors appeared in the console, and after / f reload the chunks began to be display (so that they are updated, you need to constantly write this command)

In general, it remains a little bit to finalize and probably everything should work like clockwork

**Comment by Aquerr** [comment]
Alright, let me clarify it. So, factions show up only after reloading Eagle Factions? Do they show up after server start (without reloading)? Or is the “newly claimed territories” that are not showing up? Like, everything loads properly after start but when someone claims a territory afterwards then it will not render in the map?

**Comment by Ytoblo** [comment]
> w

https://youtu.be/KDwtqst7YBA

**Comment by Ytoblo** [comment]
> Alright, let me clarify it. So, factions show up only after reloading Eagle Factions? Do they show up after server start (without reloading)? Or is the “newly claimed territories” that are not showing up? Like, everything loads properly after start but when someone claims a territory afterwards then it will not render in the map?

https://youtu.be/KDwtqst7YBA

**Comment by Aquerr** [comment]
Probably fixed in the latest dev build. I am marking this issue as **awaits release**.
