### ISSUE TITLE
Error with MySQL storage (syntax)

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#135]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.3.0

* **Plugin Version:** EagleFactions-1.12.2-v0.15.4

## What happens?

Hi! 
I tried to switch from "hocon" storage type to "mysql" storage type (created a mysql db, changed the config file), and this occured:
https://pastebin.com/V24Q5hC5
Also, after this error, /f restorebackup didn't work as intended, I think it's because of smth to do with this error.
It says a syntax error, but I'm not sure if it has something to do with the plugin or with mysql db.

## Expected result

MySQL storage working as intended. :)

**Comment by Aquerr** [comment]
Hello! Thanks for reporting the issue.

What version of MySQL are you using?

You can see what version of MySQL is compatible with EF on this page 
https://github.com/Aquerr/EagleFactions/wiki/Storage

**Comment by Faelris** [comment]
Ah. I see, I've got MySQL version 5.7.30.
So if I update it, the issue may resolve?

**Comment by Aquerr** [comment]
Yup, should work fine then.

**Comment by Aquerr** [comment]
I am closing this issue for now. Reopen it if upgrading MySQL won't help.
