### ISSUE TITLE
Feature Request /f fillclaim and /f dynmap colour

### ISSUE THREAD

**Issue by MrSeven** [Aquerr/EagleFactions#136]
**Is your feature request related to a problem? Please describe.**
Having to fill in a giant area of claims. From using /f autoclaim, I walk around a giant area of my servers map, (I'm using a realist earth style map) so when players are attempting to claim a country they walk around the border of it with the f autoclaim on. Once it makes it a closed claim, they then need to go and fill all the wilderness inside the closed claim they just made.

Allowing faction leaders to use a command like /f dynmap colour, to allow them to change the colour of their faction on the dynmap so it sticks out better instead of them all being the same colour.

**Describe the solution you'd like**
By adding a command like /f fillclaim, it will fill any wilderness inside your closed off claims. This is particularly nice to have when considering some of the borders are not perfect squares.

**Describe alternatives you've considered**

**Additional context**
Would be nice to see implemented if possible,

**Comment by Aquerr** [comment]
@MrSeven Hello! Thank you for your feature request.

I can tell that `/f fillclaim` command is something that is in my TODO list but I don't have ETA at this moment.

Where it comes to `/f dynmap colour` then I can say that I am planning to bound faction area colour to faction tag colour. So basically, the colour you pick for your tag will be also used for your faction area on dynmap.

**Comment by MrSeven** [comment]
Oh that's awesome, I'm glad to hear that sometime in the near future both those will be implemented!
