### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by Faelris** [Aquerr/EagleFactions#138]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.3.0

* **Plugin Version:** EagleFactions-1.12.2-v0.15.4

## What happens?
Hi!
From #135 I upgraded MySQL to 8.0.23. 
Here's what I get now:
https://pastebin.com/nLkJch7W
And again, after I try restoring from hocon backup it just leaves blank space in /f list.
Can it be that I didn't upgrade to higher version properly? The DB for Eaglefactions was created after I upgraded mysql and restarted the server with updated Eaglefactions config file.
Or can it be a sponge issue?

**Comment by Aquerr** [comment]
I completely forgot about this issue... Closing it as eventually got fixed by me.
