### ISSUE TITLE
Adding faction banks, and power through money/property.

### ISSUE THREAD

**Issue by cutethingg** [Aquerr/EagleFactions#139]
As of now, the only way to gain power is through PvP and being online. I believe it would diversify this plugin a lot more to add economy, giving players a different way to grow their faction peacefully. 

The first part to this would be a faction bank, and the inclusion of factions (the faction itself) being able to hold power. Faction power is currently calculated by adding up the power of each member. This system is good, but it feels empty without another option to grow your faction. I suggest allowing the faction to earn power through money deposited in the clan bank, or through the total value of all goods stored inside faction-territory-chests. 

This would most likely be done through a config, where owners could customize the price of every minecraft item and add in custom IDs for modpacks. For example, if a diamond block is worth 0.05 power, and the faction has 64 diamond blocks stored inside claimed territory in chests, your power would increase 3.2 power (0.05*64).

For the bank, another config option could be listed for how much power is worth. For example:
```
#Power prices for the clan bank. Clan will gain 0.05 power for every X amount in their bank (Default: 500):
econ-power-price: 500
```

I am more stoked about the property idea than I am about the bank. I'd love to see this be included.

**Comment by Aquerr** [comment]
As because I am cleaning all issues now and I has been some time since this issue got opened, I will be closing it.
Feel free to reopen or make a new one if you see such need.

Also, this feature request will be continued in EF-s add-on https://github.com/Aquerr/EagleFactions-Economy
