### ISSUE TITLE
Commands when /f admin activated

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#14]
Hi,

When i try to add officer when f admin activated i can't !

And don't can disband faction when i was member and admin activated !

And when admin actived, it's possible to add command like this : /f disband factionname ?

thanks

**Comment by Aquerr** [comment]
Sure thing, I will add it!

**Comment by Aquerr** [comment]
This feature has been added now!

It will be available in the next release!

I am closing this issue.
