### ISSUE TITLE
the Tinkers' Construct 2 mod's Chopper cannot destroy tree in the EagleFactions claim

### ISSUE THREAD

**Issue by FnTlv** [Aquerr/EagleFactions#142]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.4.8-RC4141

* **Plugin Version:** 0.16.0

## What happens?
My English is not very good, please forgive me

When I use the Tinkers' Construct 2 mod's Chopper to break trees in the EagleFactions claim, the trees are not broken, but the wood is dropped，such as the video
https://youtu.be/ziH8c1h1UnA

## Expected result

Destroy trees should trees be destroyed

## More information
TConstruct-1.12.2-2.13.0.183

**Comment by Aquerr** [comment]
Hello! Thanks for report! I will look into it asap.

Could you tell me what is your rank in the faction? And is your rank permitted to destroy blocks in **/f perms** command?

**Comment by Aquerr** [comment]
Hmmm.... I just did it myself and it is working without any issues for me.

I tested it in the following way:
 - I am the member of a faction
- That faction owns a claim where a tree is growing
- That faction has DESTROY permission allowed for members in **/f perms**.
- I used a lumberaxe and successfully chopped down tree.

I guess I will need more information. 
Are you in a claim that belongs to your faction? Or alliance? Or enemy?
Also, tell me your Forge version.
Also, could you send me your server's config file for eagle factions? It is located in serverdir/config/eaglefactions/Settings.conf

**Comment by FnTlv** [comment]
> Hmmm.... I just did it myself and it is working without any issues for me.
> 
> I tested it in the following way:
> 
> * I am the member of a faction
> * That faction owns a claim where a tree is growing
> * That faction has DESTROY permission allowed for members in **/f perms**.
> * I used a lumberaxe and successfully chopped down tree.
> 
> I guess I will need more information. Are you in a claim that belongs to your faction? Or alliance? Or enemy? Also, tell me your Forge version. Also, could you send me your server's config file for eagle factions? It is located in serverdir/config/eaglefactions/Settings.conf

Thank you，I solved this problem,when i set "protect-from-mob-grief = true",This problem arises.
when i set "protect-from-mob-grief = false"，It won't happen again.

**Comment by Aquerr** [comment]
Thanks for information!

I see that it is something that cannot be fixed easily. 
EF does not get information from Sponge about who destroyed the block, thus EF prevents the block from being destroyed as it treats that as mob-grief.

If you are okay with using **protect-from-mob-grief=false** then I will close this issue.

**Comment by FnTlv** [comment]
Yes，that's ok.
Thanks for writing such a great plugin.
