### ISSUE TITLE
/f kick

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#15]
## Environment

* **Sponge Version:** 1.11.2

* **Plugin Version:** 1.11.2-v0.9.5

## What happens?

the /f kick command do this error : 
You can't kick this player

## Expected result

Write here what or how should it work.

## More information

If you want to inform something more then write it here.

**Comment by Aquerr** [comment]
I will check this out!

**Comment by yodaa59** [comment]
And, when we add officer, it say "players" instead of the name of the player

**Comment by Aquerr** [comment]
You were trying this as an admin?

**Comment by yodaa59** [comment]
nope as client

**Comment by Aquerr** [comment]
Okey, I will check this... I think I already fixed the problem with kicking.
I might upload an fix today.

I will inform you about it here.

**Comment by Aquerr** [comment]
Is should be fixed now in 0.9.6.

You can check if it works. If it does then go ahead and close this issue. 😄

**Comment by yodaa59** [comment]
Ok i tried it tomorrow :) and i tell you the result :)

**Comment by yodaa59** [comment]
Hi,
It's good for the kick command :)
thanks
