### ISSUE TITLE
Interact in safezone

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#16]
## Environment

* **Sponge Version:1.11.2

* **Plugin Version:0.9.6

## What happens?

The player can't interact with vanilla chests but he can with modded chest

## Expected result

Write here what or how should it work.

## More information

If you want to inform something more then write it here.

**Comment by Aquerr** [comment]
Did you try giving the player Interact permission? `eaglefactions.safezone.interact`

**Comment by yodaa59** [comment]
yes he have

**Comment by Aquerr** [comment]
Do you get any message while doing it?

I have just tested it on my server and it works correctly. Both for chests from mods and from minecraft.
It works for me with `eaglefactions.safezone.interact` only.

**Comment by Aquerr** [comment]
Any update on this?
Is it still not working?

**Comment by yodaa59** [comment]
with the christmas i can't test it :p i try it tomorrow :)

thank a lot

**Comment by Aquerr** [comment]
🎄 Merry Christmas 🎄

Hear from you Tomorrow then 😃

**Comment by yodaa59** [comment]
apparently it's good, if i view another time an error i tell it to you :)

thank for all

**Comment by Aquerr** [comment]
Good to hear!
