### ISSUE TITLE
Require blocks/items to create a faction.

### ISSUE THREAD

**Issue by BitCrack** [Aquerr/EagleFactions#17]
I don't know if I can post it here, if not sorry for spam.
So I remember somewhere that possibly on MCFactions plugin you could set it so you need to have blocks/items in your inventory to create a faction (you could also set different blocks/items to each rank like less blocks/items for vip). Could you please add it? Thanks.

**Comment by Aquerr** [comment]
Sure thing!

I am already planning about adding this in the next update! 😄 

Regards

**Comment by BitCrack** [comment]
Oh, thanks!
Can I get a small sneak peak about around when it'll be released?

**Comment by Aquerr** [comment]
Honestly, I have no idea.
All depens on how much free time I will have... but I will try to do it as soon as possible.
It will come this month for sure 😛

**Comment by BitCrack** [comment]
Ok, thanks.

**Comment by Aquerr** [comment]
Creating Factions by items can be found now in the newest release of Eagle Factions - 0.9.7

I am closing this issue. 😄
