### ISSUE TITLE
error while executing command

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#19]
## Environment
same as before

I have error when we try to add ally

When i run the command : /f ally add <name> 
i have this result : Error occured while executing command : No value present

Can you try to solve it ?
Thanks

**Comment by Aquerr** [comment]
I will take a look at this.

**Comment by Aquerr** [comment]
I have just tested it and it works fine on my server.

Can you give me more informations about this? Screenshot of console window? Or even a log file?
Describe as much as you can so I will be able to help you.

**Comment by yodaa59** [comment]
i have tested it another time and it's work !
i dont understand why

So sorry for taking your time
