### ISSUE TITLE
Factions Leaderboard

### ISSUE THREAD

**Issue by Colton-Slayden** [Aquerr/EagleFactions#20]
## Environment

* **Sponge Version:** <spongeforge-1.10.2-2477-5.2.0-BETA-2731>

* **Plugin Version:** <EagleFactions-1.10.2-v0.9.6>

## What happens?
I was wondering if you planned to add a command to show top factions by there power/money in a list.
Planning on making a server where this would need to be a thing and i believe many other people would want the same thing.
Thank you in advance for all your hard work. 

<Write here what is happening.>

## Expected result

<Write here what or how should it work.>

## More information
The leader board would be similar to the /f list command put would not have the SafeZone or WarZone on the list and possible economy support as well to show power and wealth

Possible to allow color codes/formatting to be used in faction names/tags

**Comment by Aquerr** [comment]
Hmmm... I was not planning something like this but It may be a cool idea.

I will try to make a simple „Top List” until the next release which will be available by typing „/f top” or something like that.

When it comes to colors in tags/names, I have in mind to do this. I don’t know when but for sure as soon as possible. :)

Regards

**Comment by Aquerr** [comment]
Top Command has been added now to Eagle Factions in the newest release - 0.9.7

I am closing this issue but economy integration will stay in my mind and I will try to do something with this in the future. 😄
