### ISSUE TITLE
[1.10.2] Editing prefix set by faction

### ISSUE THREAD

**Issue by abused** [Aquerr/EagleFactions#22]
## Environment

* **Sponge Version:** spongeforge-1.10.2-2477-5.2.0-BETA-2731

* **Plugin Version:** EagleFactions-1.10.2-v0.9.5

## What happens?

Faction tag prefix along with rank

## Expected result

<Write here what or how should it work.>

## More information

I was wondering if there was any way to disable the display of the rank within a faction from being displayed as a prefix when the player is chatting, like leader, or officer, etc. I'd like to just have it as the tag along with my own ranks from luckperms is that currently possible? Or even being able to edit how its displayed so that it fits in with prefixes from other mods, like for example i have https://gyazo.com/e6082383444a5f01de4fae3562110708 and i personally dont feel like it fits in, being able to edit that might also be a nice feature

**Comment by Aquerr** [comment]
It is not currently possible but in the next update you will be able to turn off “faction’s ranks”. :)
(It will be possible to turn off factions tags too)

I like the idea about editing how prefixes are displaying. I will have that in mind and maybe add something that will allow it. 😄

**Comment by abused** [comment]
all right thanks! its cool how it works but i feel like it just takes up too much chat space is the issue

**Comment by Aquerr** [comment]
Yea, I know.

I have already heard it from some people and I noticed it myself.

**Comment by Aquerr** [comment]
Disabling faction ranks like Leader And Officer can be disabled now in the latest release - 0.9.7

I am closing this issue.
Option for editing prefixes will be in my mind and I will maybe implement something like this in the future.
