### ISSUE TITLE
Obligatory API 7 Issue :-)

### ISSUE THREAD

**Issue by ryantheleach** [Aquerr/EagleFactions#24]

**Comment by Aquerr** [comment]
What does it mean? An update to API 7? 😄 orrr? something that I don’t know? 😛

**Comment by ryantheleach** [comment]
Yes, but you answered on the forums :)

**Comment by realKSMC** [comment]
Btw it works with 1.12 partly.

**Comment by Aquerr** [comment]
Download for version compatible with API 7 will be available when plugin hits 0.9.9 :)

**Comment by Aquerr** [comment]
Version 0.9.9 has been released today for API 5, 6 and 7. 😄

I am closing this issue.
