### ISSUE TITLE
DynMap Support

### ISSUE THREAD

**Issue by crymates** [Aquerr/EagleFactions#25]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add support for dynmap. E.g. the plugin "Nations" already got this done, so there should be an way :)
It's just the BEST option for an overview and look for unclaimed chunks in ur territory.

**Comment by realKSMC** [comment]
Yes btw, I noticed the '/f automap' command. So it is an totally good option, but I still like to see the areas on dynmap :)

**Comment by Aquerr** [comment]
I like the idea with the Dynmap support. That would be cool. I will see what I can do with this. ^^

**Comment by Aquerr** [comment]
Added in #95. This feature will be a part of the next release.

**Comment by IteratorW** [comment]
It can be already downloaded if needed :)
![image](https://user-images.githubusercontent.com/30198566/61172187-5d472100-a59a-11e9-8245-901f676aa3cf.png)

**Comment by jaredallard** [comment]
@Aquerr What's the status of this?

**Comment by Aquerr** [comment]
„Status: Awaits Release”
