### ISSUE TITLE
Add claim time option for unclaimed chunks

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#26]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Option request

Like it already exists when attacking an faction, can u add an option so that some time is needed to claim an land? By default it could be inactive.

**Comment by Aquerr** [comment]
The faction that has been attacked (by using /f attack command, not by attacking with sword etc.) should have claiming blocked under 2min. Have you seen it? or is it not working?

**Comment by realKSMC** [comment]
That should work (not tested yet), but I'd like to get this option also for wilderness chunks. That's it :)

**Comment by Aquerr** [comment]
Ahhh... I misunderstood your question... sorry.

An option for claiming "unclaimed" territories with some sort of delay sounds ok. I will add this in the 0.9.9. 🙂

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
