### ISSUE TITLE
Add claim item option

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#27]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add an option so that u need specific items to claim an area, like the factions create option. By default it should set to false.

**Comment by Aquerr** [comment]
Sounds like a cool feature.

I will try to add it in 0.9.9 release. 😄

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
