### ISSUE TITLE
Create faction using items failed

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#28]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## What happens?

I turned on the option that for creating an faction items are needed and edited the items in config to the following:

`
            items=[
				"minecraft:sand|1"
            ]
` (multiple lines seems not to work here on github..)

Ingame command:
`/f create 'GMR' 'German Minecraftreich'`

## Expected result

I get `You do not have enough.....` as an ingame message and are not able to create the faction with 1 sand.

**Comment by Aquerr** [comment]
Hmmm... strange... I will take a look at this.

**Comment by realKSMC** [comment]
Tried `items=[ "minecraft:sand:0|1" ]` - when I now try the create command ingame I get no more error message, but the faction still does not get created.

**Comment by realKSMC** [comment]
Is there any more permission needed except `eaglefactions.command.create`?

**Comment by Aquerr** [comment]
`eaglefactions.command.create` is the only permission for creating a faction. 

I am testing this now.

**Comment by realKSMC** [comment]
Ok, thx alot.

**Comment by Aquerr** [comment]
Damn it... It works on 1.11.2.

I will need to recode it.

It should be fixed in 0.9.9 release. Don't know when it will come out but for sure it will be fixed.

**Comment by realKSMC** [comment]
Great, thx :)

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
