### ISSUE TITLE
Attack at night only

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#29]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add an option so that attack an faction is just possible at night.

**Comment by Aquerr** [comment]
So... /f attack is available only at night? or something more?

**Comment by realKSMC** [comment]
Just that, exactly.

**Comment by Aquerr** [comment]
Alright! I will add this. You will be able to turn this feature on in the config file. :)

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
