### ISSUE TITLE
TAB between /f info FACTION

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#30]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add that u can TAB between the factions while in `/f info`

**Comment by Aquerr** [comment]
This is something I was already planning :)

It will be implemented as soon as possible ^_^

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
