### ISSUE TITLE
Improve /f info

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#31]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add that by default `/f info` shows the info about the faction u are a part of.

**Comment by Aquerr** [comment]
Sure thing! It will be added! :)

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
