### ISSUE TITLE
Extra permission eaglefactions.command.info.others

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#32]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add that there is an extra permission to see the faction info about other factions.
By default you should just able to see the info about ur own.

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

There may be a bug with `eaglefactions.command.info` permission but `eaglefactions.command.info.self` and `eaglefactions.command.info.others` should work fine.

I am closing this issue.
