### ISSUE TITLE
Fire in SafeZone and WarZone

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#33]
The moment when no block can be damaged, but set on fire. This time it happened by an thunderbolt.
Pls fix :)

![grafik](https://user-images.githubusercontent.com/22519816/34651943-084c8304-f3d8-11e7-8a71-8228e96315ee.png)

**Comment by Aquerr** [comment]
You just explained to me how did this happend before (I have noticed this long time ago and I couldn't figure how).
Thunderbolt... that's right! It will be fixed!

Fire will be allowed in the SafeZone & WarZone but only player with permission will be able to set it.

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
