### ISSUE TITLE
Claming 11/10

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#34]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## What happens?

If u claim an area, actually u are able to claim 11/10 with a power of 10/10.
Pls fix it :)

**Comment by Aquerr** [comment]
Sounds Strange... I will look at this.

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
