### ISSUE TITLE
Block /f home after death in own area for some time

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#35]
## Environment

* **Sponge Version:** 1.10.2

* **Plugin Version:** 0.9.7

## Feature request

You should also block the `/f home` command for 2 minutes when you got killed IN YOUR OWN AREA.
Pls add this :)

**Comment by Aquerr** [comment]
I think it will be best to have an option for turning this feature on in config file as well as changing the amount of time that player needs to wait.

**Comment by realKSMC** [comment]
Absolutely :)

**Comment by Aquerr** [comment]
This should be added in the newest release 0.9.9 

I am closing this issue.
