### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#37]
## Environment

* **Sponge Version:** 1.10.2
* **Plugin Version:** 0.9.7

## Question

Does flags like `use doors and chests, place, destroy` already exists? (already for who, like leader, officer, citizen, ally)
It should be controlled by the leader.

*An example:*

``WHO | USE | PLACE | DESTROY``
``LEADER | TRUE | TRUE | TRUE``
``OFFICER | TRUE | TRUE | TRUE``
``CITIZEN | TRUE | TRUE | FALSE``
``ALLY | TRUE | FALSE | FALSE``

Changeable with `/f flags` and clickable in chat :)

**Comment by Aquerr** [comment]
Sounds like a something I don't want to deal with right now. I may consider it as a long term feature.

I will let this issue stay open so that I will remember this.

**Comment by Aquerr** [comment]
I’ve been thinking about this a lot now and I need to say that the example you provided is very good.

I am thinking about adding something that will look exactly like your example.

It may be ready to use in the next version :)

**Comment by Aquerr** [comment]
Flags are implemented and ready for testing now. I will release a new version this weekend that will contain this feature.

**Comment by Aquerr** [comment]
Anyone who wants to test this feature can download this PRE PRE Release 😛  [EagleFactions-1.12.2-0.9.13pre](http://www.mediafire.com/file/cydyy5ha6dj4maz/EagleFactions-1.12.2-v0.9.13.jar) 

If you will find any problems with flags then message me here (or open new issues with more specific informations).
