### ISSUE TITLE
Progress 0.9.9

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#39]
## Question

What about 0.9.9? What is planned, when it will release? :)
Do u have some infos for me? I'm totally hyped for it :P

**Comment by Aquerr** [comment]
I have already started updating the plugin as you may have already noticed. But there are many things still which need to be done.

Right now I can say the 0.9.9 will come in this month... but I can't tell when exactly.

**Comment by realKSMC** [comment]
Wonderful :)
I switched btw to API7, so if it's not really needed, u can stop ur work for API5.

**Comment by Aquerr** [comment]
I will not, 1.10.2 must be updated as well as other versions :stuck_out_tongue:

**Comment by realKSMC** [comment]
So, what's the status? :)
