### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Eufranio** [Aquerr/EagleFactions#4]
I have a few questions, like: What is the SafeZone and where is it located? What is the WarZone and where is it located? Can we expand the SafeZone by claiming our spawn? Can we set the WarZone to be a certain area?

Looks like the plugin is missing some documentation. I'd like to help with it, but I don't know nothing atm (and cannot learn, no docs)...

**Comment by Aquerr** [comment]
Documentation is under construction.

SafeZone and WarZone works the same like in the MassiveCraft's Factions plugin.

You need to join to SafeZone or WarZone to be able to claim lands for these factions.

SafeZone is basically a place where you are safe. Players and mobs can't hurt you. Many servers use SafeZone as a spawn point.

WarZone is a place where you can fight but you can't build or use chests, levers, doors etc.

I will try to update the wiki in this week. :)

**Comment by Eufranio** [comment]
How can factions "destroy" other factions territories that have low power?

**Comment by Aquerr** [comment]
As it is noted in ReadMe.md... this feature is not implemented yet.
