### ISSUE TITLE
Under attack info message

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#40]
## Environment

* **Sponge Version:** 1.11.2

* **Plugin Version:** 0.9.7

## Feature request

Pls add that a faction gets an message when an chunk is under attack - also when an chunk got destroyed.

**Comment by Aquerr** [comment]
No problem ^^

**Comment by Aquerr** [comment]
I am thinking how this should work.

Should players get a message only once when attack is started (when enemy player type **/f attack**) or should they get a message every second?

**Comment by realKSMC** [comment]
Only once per attack.

**Comment by Aquerr** [comment]
That’s what I thought too. It is fixed and awaits its release. :)

**Comment by Aquerr** [comment]
This should be added in the newest release.

I am not sure if I added a message about destroying claim. If I did not add it then I will do it in the next version.
