### ISSUE TITLE
License

### ISSUE THREAD

**Issue by realKSMC** [Aquerr/EagleFactions#41]
## Environment

* **Sponge Version:** 1.11.2

* **Plugin Version:** 0.9.7

## Question
E.g. I refinance my server with donations. Am I allowed to use the plugin in that way?

**Comment by Aquerr** [comment]
Sure! No need to ask me for permissions. 😄

**Comment by realKSMC** [comment]
And is there any way to donate a part of it to you when the time comes? (project starts around march)

**Comment by Aquerr** [comment]
There will be a link for it on spongepowered forum and maybe here too :)
