### ISSUE TITLE
Multiserver platform :)

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#42]
Hello,

It's possible to add functionnality for save data into MySQL ? And possibility for some serveurs can use this data for number chunks claims ? i think it was a good upgrade

With this, on other servers (like miner world, or another faction world if the first is full) people can have tag ingame, claimed chunk for all platform, ...

Thanks for your reply :)

**Comment by Aquerr** [comment]
Sounds like a big feature, and I like it.

I will have this in mind. :)

**Comment by yodaa59** [comment]
I think it's better to do it when not of lot modification, because if you do it in few months, you need to do more upgrades !

**Comment by Fungie2134** [comment]
I was going to request the same thing. Almost every big server needs that because BungeeCord is used.

**Comment by Aquerr** [comment]
MySQL is almost finished, althrough its experimental version is available to use since **0.11.0**.
