### ISSUE TITLE
New chunk claiming map idea !

### ISSUE THREAD

**Issue by Lajtmen** [Aquerr/EagleFactions#43]
THIS WOULD BE AWSOME : (this is how chunk claiming works in FTBU mod)
Just clicking on the map and you claim a chunk. left click claim/right unclaim 
And it could be connected with Xaero's Minimap or something. (not claiming , just that u can see the chunks)

![maxresdefault](https://user-images.githubusercontent.com/33398720/35188452-b6bbd11c-fe35-11e7-8424-b3c04d88c54c.jpg)

**Comment by Aquerr** [comment]
Yeah, I know this mod and I like how it works.
I am afraid that It may not be possible to do such things in the plugin. I think such maps can be made only in mods but I may be wrong.

I can make a little research on this, but for now I think the only option for such map is the existing **/f map** command which allows you to claim territories. It works basically the same as the map from FTB Utils.

Also, It could be possible to make a map in the “player inventory”. By this, I mean... a player could type **/f map** in the chat and then a map made of blocks/items could be shown for the player in the doublechest-like inventory. (You may have seen something similar on some Spigot Servers)

**Comment by Aquerr** [comment]
I am closing this because I will not be possible to make such map in the plugin.
Only solution for map is to use currently existing `/f map` command which allow claiming by clicking the points on the map.
