### ISSUE TITLE
No power increase after killing a player

### ISSUE THREAD

**Issue by Lajtmen** [Aquerr/EagleFactions#48]
No power increase after killing player.

**Comment by Aquerr** [comment]
Hmmm... before I look at this I need some more informations...
Which version of Sponge and EagleFactions are you using?

**Comment by Lajtmen** [comment]
spongeforge-1.10.2-2477-5.2.0-BETA-2698 , EagleFactions-v0.9.9 (Beta)

**Comment by Aquerr** [comment]
Alright, I will take a look at this today.
This happens when you kill someone from other faction that is not your ally right?

**Comment by Lajtmen** [comment]
it happens when i kill anyone , with no faction or in faction

**Comment by Aquerr** [comment]
Ok, I think I know what may be wrong.

I will try to release a fix today.

**Comment by Lajtmen** [comment]
ok thanks

**Comment by Aquerr** [comment]
This should be fixed in version 0.9.10 which is available to download at releases page.

I am closing this issue. If this error will occur again then please reopen this issue. :)
