### ISSUE TITLE
Only OP's Can Claim Land

### ISSUE THREAD

**Issue by mr7ego** [Aquerr/EagleFactions#49]
## Environment

* **Sponge Version:** <Your Sponge Version> beta 2857

* **Plugin Version:** <Your Plugin Version> Eagle factions 1.12.2

## What happens?

Only Op's can claim land

## Expected result

Every player should be able to claim land

## More information

I know this problem may sound trivial and easy to fix, this is my first time with sponge plugins, plugins in general, owning a server in general, I looked up permissions in the Eagle Factions wiki, but I don't know where to type them, I looked up on youtube for any information, couldn't find any, if there is any way anyone could help that would be much appreciated.

**Comment by Aquerr** [comment]
I will take a look at this.

Can you please tell me if you are using any permissions mamagment plugin? Ex. **Luck Perms** Or **PermissionsEx**

**Comment by mr7ego** [comment]
I am not using Luck Perms or PermissionsEx

**Comment by Aquerr** [comment]
Are you using any other plugin for managing permissions on your server?

If not, then the first thing you can try out is to add a permissions managment plugin like **Luck Perms** (it can be anything, depends on your preferences) and try adding there permissions from Eagle Factions.

If you need any help with setting up such plugin then message me here and I can provide you a simple example for how you can do it.

**Comment by mr7ego** [comment]
no, the only plugin I am using is yours (Eagle Factions) and I will try now

**Comment by mr7ego** [comment]
okay i have figured it out thank you, but does the eaglefactions.command give all the commands even the admin commands and if not, is there a way to set all commands for all the player commands and not admin commands.

**Comment by Aquerr** [comment]
Yes, `eagleafactions.command` gives access to all commands inclusive admin commands, so you will need to type all permissions manually :/ 

I am planning to add only one permission for player command and only one permission for admin commands in the next version. :)

**Comment by mr7ego** [comment]
oh okay and yeah that will be handy ahaha. Thanks again for your help. :D
