### ISSUE TITLE
Chat formatting support

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#5]
Hello,

It's possible to use a préfix with plugin permissions ?

I use luckperms and the prefix not used ! i know luckperms work with vault for use prefix in game !

Thanks for reply

**Comment by Aquerr** [comment]
It should work fine. I was testing this with LuckPerms one month ago and It worked, but I can take a look at this again. 

Regards

**Comment by yodaa59** [comment]
I have this error message in console when someone speak 

 Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=eaglefactions, name=Eagle Factions, version=0.9.4, description=A factions plugin that will make managing your battle-server easier. :), source=/home/minecraft/Serveurs/Pvp/mods/EagleFactions-v0.9.4.jar}

**Comment by Aquerr** [comment]
Could you send me your plugins that uses chat formatting? or your luckperms settings?

I would like to test this somehow but I can't now.

It is working fine with LuckPerms for me.

**Comment by yodaa59** [comment]
I don't kno why, but i now have no errors ! (i think it's because i updated a plugin but i'm not sure)

If this bug comming another time i comming back :)

thank for all

**Comment by Aquerr** [comment]
Good to hear!
Have a good day!
