### ISSUE TITLE
Phase incompatibility detected! Attempting to switch to an invalid phase!

### ISSUE THREAD

**Issue by TomTheHero** [Aquerr/EagleFactions#50]
* **Sponge Version:** spongeforge-1.10.2-2477-5.2.0-BETA-2790.jar

* **Plugin Version:** EagleFactions-1.10.2-v0.9.9.jar

This is spamming my console and i believe eaglefactions is causing it https://pastebin.com/1R2iArzR

**Comment by TomTheHero** [comment]
I whould also like to suggest adding a configurable cooldown to the faction sethome command and how long someone must stand still in order to teleport to it to prevent people from teleporting out of combat.

**Comment by TomTheHero** [comment]
And that thing i pastebinned is spamming my console yet again

**Comment by Aquerr** [comment]
I will try to analyze what is that spamming error you are getting.

The second thing about „setting a wait time before teleporting home” was already in my plans. I will try to add it as soon as possible.

**Comment by TomTheHero** [comment]
And Apparently there is no way to kick someone from your faction xD

**Comment by Aquerr** [comment]
What? Does **/f kick** not work?

**Comment by TomTheHero** [comment]
One of my staff which plays on the server is doing /f kick AwesomeFTW (AwesomeFTW is a playername) and it says too many arguments

**Comment by Aquerr** [comment]
Damn... I will try it myself.

Temporary solution for this may be removing the given player from the faction in "factions.conf" file and then reloading the plugin with **/f reload**.

**Comment by Aquerr** [comment]
I have tested it now and it works... hmmmm... the question is... why is it not working for you. 🤔

**Comment by TomTheHero** [comment]
And this discord plugin is sending faction chat to discord https://forums.spongepowered.org/t/magibridge-a-utility-discord-minecraft-chat-relay-plugin/19796

**Comment by Aquerr** [comment]
You mean... internal faction's chat?

**Comment by TomTheHero** [comment]
I ques so

**Comment by Aquerr** [comment]
So if a player writes something while being in [Faction] Chat Type... then message is sent to the Discord?

**Comment by TomTheHero** [comment]
Yep

**Comment by Aquerr** [comment]
Ok, this is a thing I can't fix right now.
A connection between MagiBridge & Eagle Factions is needed to make it works.

I made a separate issue for this and marked it as a enhancement. All informations about this topic will be posted there. #52

**Comment by Aquerr** [comment]
@TomTheHero Could you check when does the error from the console show?
Check if it is happening if player is moving, jumping, flying, using a command. That would help a lot. :smile:

**Comment by TomTheHero** [comment]
From what i can see within the console it happends at random

**Comment by Aquerr** [comment]
I have read some informations about this. It looks like it may be something that comes directly from Sponge and not from Eagle Factions.

For example:
1. https://github.com/SpongePowered/SpongeForge/issues/1047
2. https://github.com/SpongePowered/SpongeForge/issues/1856

Could you try to update (or downgrade) your SpongeForge.jar to the latest version and check if it helps?

**Comment by TomTheHero** [comment]
Well, lets hope they fixed it for 1.12.2 aka api 7 as they no longer support 1.10.2 and never fixed it for 1.10.2

**Comment by TomTheHero** [comment]
Btw, many projecte tools are able to dupe things with faction claims(they have an aoe ability), they will not breaks blocks but they blocks will be dropped, the EFLN from tinkers construct completely bypasses it and there are many more things like that

**Comment by Aquerr** [comment]
Tell me the name of the tool so I can check this myself. It will help with making a fix for this :)

**Comment by TomTheHero** [comment]
I am not able to name them right now but i am quite sure that the shovels and red matter pickaxes did that(do note that you must charge them to enable to AOE thing) and i am sure that it happened with both the dark and red matter axe when used on trees

**Comment by Aquerr** [comment]
Alright!

I will look at this! :)

**Comment by Aquerr** [comment]
@TomTheHero I have looked at the problem with ProjectE yesterday.
I am afraid there may be no way to fix this but I will try to do more research today. :)

**Comment by TomTheHero** [comment]
Any luck yet?

**Comment by Aquerr** [comment]
I had no time to look at this before.

I will try to do something at the weekend.

**Comment by Aquerr** [comment]
@TomTheHero I was looking at the problem with ProjectE tools before... and it looks like I can't do anything about it.

I may look at this again in the future but I don't know if I will be able to fix this. Please open a new issue for this if you can. Write there about Project E tools.
