### ISSUE TITLE
Delay for teleporting after using /f home command

### ISSUE THREAD

**Issue by Aquerr** [Aquerr/EagleFactions#51]
## Feature Request

It should be possible to set a delay for teleporting after using **/f home** command.

Option for it should be placed in main config file.

**Comment by TomTheHero** [comment]
Please add both a warmup time during which you'll have to stand still in order to teleport and a cooldown for using the command itself unless it got cancalled because you moved and how about adding some anti combatlogging function

**Comment by Aquerr** [comment]
Sure, It will be added. Both wait time and cooldown. 😄

PVP-Logger may be added too in the future. I just need more free time to do this 😛

**Comment by Aquerr** [comment]
Delay and cooldown has been added in the latest release.

Feel free to reopen this issue if something will not work properly :)
