### ISSUE TITLE
Integration with MagiBridge

### ISSUE THREAD

**Issue by Aquerr** [Aquerr/EagleFactions#52]
# Feature Request

We should try to make a connection between **Eagle Factions** & **MagiBridge** and do something that will tell **MagiBridge** to send only **Global** chat messages to Discord.

## Approach 1

**MagiBridge** can have an API. It could be worth checking it out!

## Approach 2

**MagiBridge** uses chat channels from **Ultimate Chat** or **Nucleus**.

It should be possible to use API from one of these plugins and modify existing way for creating channels in **Eagle Factions** so that it will work in the same way but with help of these plugins (for the compatibility with **MagiBridge**).

Such APIs should be optional in **Eagle Factions** to keep independence.

If APIs will not be found by **Eagle Factions** then the plugin should work like it does today.

## Cool Idea

What is also worth trying is to set up Eagle Factions chat channels in such way that server owner will be able to send chat messages (from Global, Faction chats) to respective chat on Discord.

For example...
**Channel 1** - For Global Chat where all messages are being sent
**Channel 2, 3, 4 ...** - For Factions' Chats where only factions messages are sent

The owner would be able to set up a bot for respective channel and add it to respective chat on Discord.
Sounds easy, but is it difficult?

**Comment by CraftalotReloaded** [comment]
Any progress on this?

**Comment by Aquerr** [comment]
@CraftalotReloaded None. I actually had no time for looking at this yet.

**Comment by Eufranio** [comment]
Hi, I'm the MagiBridge developer. I see you have created [custom MessageChannels](https://github.com/Aquerr/EagleFactionsAPI/tree/master/src/main/java/io/github/aquerr/eaglefactions/api/messaging/chat), so I can check for those on the MagiBridge side to ignore private (ally/faction) messages. If you want to still send those to Discord, MagiBridge has a nice API for sending and receiving messages, with placeholder support, mentions and etc, you should consider looking into it.

**Comment by Aquerr** [comment]
@Eufranio Thank you for information! It would be actually cool to somehow send those messages to discord channels. So that we can connect each faction to a separate private discord channel where people gets their alliance/faction messages. I will into the MagiBridge's API and try to come up with something.

Ps. I think the [if statement](https://github.com/Eufranio/MagiBridge/blob/e4910acb462a1a1f7b6554722ca66724fc636ee9/src/main/java/com/magitechserver/magibridge/listeners/VanillaListeners.java#L88) that checks if channel is faction/alliance channel in MagiBridge could be improved. I see that **Impl** classes are used there instead of interfaces. If they will change in the future then this code will break. **EagleFactionsAPI** should be used here instead of using real implementation classes in my opinion. I can make a pull request for it if it is ok for you?

**Comment by Eufranio** [comment]
Actually I had changed it to the API classes a bit ago, just forgot to commit it.

**Comment by Aquerr** [comment]
As because I am cleaning all issues now and I has been some time since this issue got opened, I will be closing it.
Feel free to reopen or make a new one if you see such need.

As far as I know, MagiBridge contains code that integrates with EF channels in 1.12.2.
