### ISSUE TITLE
cant attack faction, power is too high even if is power lower than mine

### ISSUE THREAD

**Issue by Lajtmen** [Aquerr/EagleFactions#53]
i want to attack friends faction which has power 6 and i have 10 , it says cant attack faction, power is too high. even if is power lower than mine. ( SpongeForge-1.10.2-2477-5.2.0-BETA-2793 )

**Comment by Aquerr** [comment]
Look here --> [Destroying enemy factions](https://github.com/Aquerr/EagleFactions/wiki/Destroying-other-factions)

>You can destroy other factions’ lands only if:
>- Their power is lower than 20% of their max power.
>- Your faction’s power is higher than their power.

Your friend's faction needs to have **20% of its maximum power**. If he is alone in the faction then his faction must have **2 power** if you want to attack it. 🙂

**Comment by Lajtmen** [comment]
ok.
