### ISSUE TITLE
throwable explosive items can destroy enemy faction land 

### ISSUE THREAD

**Issue by Lajtmen** [Aquerr/EagleFactions#54]
throwable explosive items can destroy enemy faction land. granades for example

**Comment by Aquerr** [comment]
Wow, that's interesting issue. I think I have tested it before but I can do it again ^^

**Comment by Aquerr** [comment]
Okey, so the thing is... everything in a claimed territory (not in the SafeZone) is destroyable by explosoves. (By creepers, tnts, granades etc.)

It is not a bug actually, it is a thing that was planned and implemented.

I can add an option to the config file where it will be possible to disable it :)

**Comment by TomTheHero** [comment]
Also try to protect them better against other area of effect things such as tools that break multaple blocks while only touching one

**Comment by Aquerr** [comment]
@Lajtmen This should be fixed in the latest release.

There is a node in `Setting.conf` called `disable-block-destroy=false`
Simply switch it to `true` to disable explosions at faction's territory.

@TomTheHero You can try out this too. It may help with your problem that you described in #50 :)
