### ISSUE TITLE
Players with player commands not able to use any commands.

### ISSUE THREAD

**Issue by Bradman12312** [Aquerr/EagleFactions#55]
## Environment

* **Sponge Version:** <1.12.2-2611-7.1.0-BETA-2955>

* **Plugin Version:** <EagleFactions-1.12.2-v0.9.10.jar>

Im currently testing this plugin on my server. plugin is in the right folders, perms are set right to the group im testing it in, but no commands work. Using Thut Perms. Group set right. Factions perm set right for the group. Cant use commands. Cant even disband faction.
Commands only work when im OP. 

## Expected result
All commands for players should be working. I followed the instructions correctly. 

## More information

using Thut Perms, and no other perms mod or faction mod. 

image of mods below
![capturemods](https://user-images.githubusercontent.com/29137210/37227432-1580fc50-2392-11e8-8612-9f69598b129d.JPG)

**Comment by Aquerr** [comment]
I will test this myself and see what I can do with it asap

**Comment by Aquerr** [comment]
I was looking at the ThutPerms's curseforge website and I found something from the author...

``` Hmm I am not sure, I had not tested this mod with spongeforge, as it was mostly made so that there was a permissions manager which didn't depend on sponge.```

Ref: https://minecraft.curseforge.com/projects/thutperms?comment=72

I think, ThutPerms may only work with permissions for mods.
Plugins permissions are managed by sponge however, so you may need something different for this (e.g Luck Perms).

I haven't tried it myself still but I think it may be a solution for this.

**Comment by Bradman12312** [comment]
Thank you! Please let me know :)

**Comment by Bradman12312** [comment]
Awesome. Thank you for looking into this. Ill swap perms plugins and see what it does. Ill keep you posted within the next hour or so. :)
Thanks for the quick reply.

**Comment by Bradman12312** [comment]
Alright, so you were right.  I swapped to Luck perms, (god its gonna take a bit to redo perms haha), but you were right. works swimmingly now. Thanks for the assist! Ill close the ticket!

**Comment by Aquerr** [comment]
Good to hear it is working now 😄
