### ISSUE TITLE
java.io.IOException: while scanning a simple key by luckperms towards 2 eaglefactions permissions

### ISSUE THREAD

**Issue by TomTheHero** [Aquerr/EagleFactions#57]
Sponge Version: 1.12.2-2611-7.1.0-BETA-2931

Plugin Version: 0.9.11

## What happens?

Luckperms runs into problems with the following 2 permissions(And these permissions do not work):

eaglefactions.player
eaglefactions.player.help

Full error: https://pastebin.com/7NCQEaYF

**Comment by Aquerr** [comment]
First thing I am thinking of is that you may have something wrong in your luckperms configuration.

However it depends on which storage type you are using... is it H2? or something else?

**Comment by TomTheHero** [comment]
I'm using .yml, and it only has problems with those 2 permissions

**Comment by Aquerr** [comment]
Strange... I have just tried it with YAML and It works fine, same for JSON and H2.

This is my `default.yml` for permission group **default**

https://pastebin.com/BZuMQikv

Can you temporary take it and try it yourself? Type `/f help` in game after copying and see if commands from **Eagle Factions** are showing in the chat.

**Comment by TomTheHero** [comment]
That is literally how my permission file starts: https://pastebin.com/N1yzEjN3

**Comment by Aquerr** [comment]
I guess... if you add a space between „-„ and „eaglefactions.player” it will be the same error?

**Comment by Aquerr** [comment]
Yup, that's it!

I have tried using your file and I got the error you described at the beginning.

I have changed now all permissions so the have a blank space between the `-` and the permission and it works fine! 😁

So they look like this:
ex.

```
- eaglefactions.player.help
- eaglefactions.player.create
- eaglefactions.player.kick
...
```

Solution: Add **a space** between `-` and `permission.permission`

**Comment by TomTheHero** [comment]
That is strange though as all other perms worked just fine without the space.

**Comment by TomTheHero** [comment]
It did indeed fix it but do add this permission to the permission list before closing this issue: eaglefactions.player.setleader

**Comment by Aquerr** [comment]
Done! Hah, don't know how I did forget about it.
