### ISSUE TITLE
Could not pass SpawnEntityEvent$ChunkLoad$Impl to Eagle Factions

### ISSUE THREAD

**Issue by TomTheHero** [Aquerr/EagleFactions#58]
Sponge Version: 1.12.2-2611-7.1.0-BETA-2931

Plugin Version: 0.9.11

The only thing i can tell about this is that sponge put this into the console: https://pastebin.com/PmiH30Dz
EDIT: Here is another event which it also had trouble with: https://pastebin.com/inaqLatQ
EDIT: Yet another one: https://pastebin.com/N9Fx9tNU
EDIT: All these errors spam my console whenever the server starts or whenever someone is online and it occurs for even more events such as for the spawner one and so on.

**Comment by Aquerr** [comment]
Looks like it may be an issue with getting a faction.

Could you send me the content of your `factions.conf` file?

**Comment by TomTheHero** [comment]
Here you go: https://www.dropbox.com/sh/ryjlzs8ltb6fsaq/AAAwe9qYfY9scEXBt7DWOuAGa?dl=0

**Comment by Aquerr** [comment]
Aha! Got it! Plugin has problem with creating a `factions.conf` file.

I am working on a fix now. Should be available soon.

Thanks for noticing this issue!

**Comment by Aquerr** [comment]
As a temporary fix for this, before I upload a new version... you can just create a directory called `data` in the `eaglefactions` directory 😛

**Comment by Aquerr** [comment]
Just released a new version that contains a fix :)
