### ISSUE TITLE
Duping items by trying to break blocks

### ISSUE THREAD

**Issue by prodkid** [Aquerr/EagleFactions#6]
Whenever a player tries to break a block that they don't have permission for they the item breaks, and respawns like normal. Example
https://gyazo.com/9d7d7c230e71456c9dd8b6689dca818b

**Comment by Aquerr** [comment]
Strange... but I will take a look at this.

Were you both in the same faction or different? Did the player that destroyed a chest get any message in the chat? Are you using the latest version?

**Comment by prodkid** [comment]
Latest version, different factions and I believe it only message was this land belongs to someone else.

**Comment by Aquerr** [comment]
Alright, I will check this out!

**Comment by prodkid** [comment]
Okay,  would it be possible for some flag options for claimed land like for example safezone and allowing interacting with signs, chests, etc in safezones.

**Comment by Aquerr** [comment]
I think that, if you give someone permission for interacting in SafeZone, then they should be able to do it.

Check **eaglefactions.safezone.interact**

**Comment by prodkid** [comment]
Yeah that seems to work thanks! Would it be possible to create a limit of members per faction as well?

**Comment by Aquerr** [comment]
Limit? Hmmm... that was not a thing I was planning.

The only person who can invite others is the faction’s leader & officers so tell them to not invite others 😝.

But I think I could add this in the next release. It would be available in config file to turn it on as well as setting how many players can join. But I am honestly not sure if it is needed.

**Comment by prodkid** [comment]
Just wanted to limit players to have not a large of a faction and I found the issue, looks like MultiMine mod is causing it :P

**Comment by Aquerr** [comment]
Alright, I will add a limitation in the next release.

So is MultiMine causing the issue with the duplicating?

**Comment by prodkid** [comment]
Yeah, removed the mod and now it's not occurring anymore.

**Comment by Aquerr** [comment]
So the issue can be closed now?

**Comment by prodkid** [comment]
I'll close for now and look into further.
