### ISSUE TITLE
Explosions are enabled in WarZone

### ISSUE THREAD

**Issue by ChrisLane** [Aquerr/EagleFactions#62]
## Environment

* **Sponge Version:** 12.2-2611-7.1.0-BETA-2996

* **Plugin Version:** 0.9.12

## What happens?
Explosions are enabled in WarZone.

## Expected result
There should be a way to disable explosions in WarZone if they're not already supposed to be.
e.g. The suggestion similar to Bukkit Factions here: https://github.com/Aquerr/EagleFactions/issues/37

**Comment by Aquerr** [comment]
A node for this will be added in the config file. 🙂

It wasn’t implemented before because I thought that WarZone should be a “WarZone”. A place where every **boom** 💥 can happen. 😛

**Comment by ChrisLane** [comment]
@Aquerr it's most useful as a buffer around SafeZone's like spawn to be honest.

**Comment by Aquerr** [comment]
I will add a node for this :)

I will inform you when it will be done 😄

**Comment by Aquerr** [comment]
Added in commit  https://github.com/Aquerr/EagleFactions/commit/95cd0450756025edfa31f7ddd5754a9431278969 😄 

You will be able to use this node in the next release! 😄 

Comment above the node may be changed because it is not so clear what it does right now.
