### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by demon57730** [Aquerr/EagleFactions#64]
EagleFactions-1.12.2-v0.9.12.jar

spongeforge-1.12.2-2611-7.1.0-BETA-2981.jar

forge-1.12.2-14.23.2.2634-universal.jar

confg

blockEnteringFactions=true

______________________________________________________________________________________________________________

when the config forbids entering a chunk of an unconnected faction and fine when the player(no faction)  enters the crash server

**Comment by Aquerr** [comment]
So, server is crashing when a player with no faction tries to enter a faction chunk?

I am going to test this myself and fix this if it will be needed

**Comment by demon57730** [comment]
I would like to give the log but when the server crash an error message runs in a loop which makes pastebin refuse the text because too long

http://rock-rp.fr/dl/console.log

**Comment by Aquerr** [comment]
Hmmm... a have seen a problem with “Phase” before... 

I will dig more into it and see if I can find any solution to this.

**Comment by demon57730** [comment]
Thank you
