### ISSUE TITLE
Getting weird error, need assistance asap

### ISSUE THREAD

**Issue by Bradman12312** [Aquerr/EagleFactions#70]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar

* **Plugin Version:** EagleFactions-1.10.2-v0.9.13.jar

## What happens? 

I keep getting this long string of errors whenever factions does something, it looks chat related but i cant tell speficially whats wrong. I tried updating both the sponge plugin and the factions plugin. As well as the reinstalling vault chat formatter. I cant tell where the problem lies. 

## Expected result

I shouldnt get a string error like i do.

## More information

Here is the error i keep getting below:

23.04 23:52:30 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task eaglefactions-S-0 owned by Plugin{id=eaglefactions, name=Eagle Factions, version=0.9.13, description=A factions plugin that will make managing your battle-server easier. :), authors=[Aquerr], source=/mods/EagleFactions-1.10.2-v0.9.13.jar}, but an error occured.
23.04 23:52:30 [Server] INFO java.lang.NullPointerException: null
23.04 23:52:30 [Server] INFO at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_151]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.logic.MainLogic.getPowerIncrement(MainLogic.java:40) ~[MainLogic.class:?]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.managers.PowerManager$1.accept(PowerManager.java:279) ~[PowerManager$1.class:?]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.managers.PowerManager$1.accept(PowerManager.java:273) ~[PowerManager$1.class:?]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_151]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:278) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
23.04 23:52:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
23.04 23:52:30 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
23.04 23:52:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
23.04 23:52:30 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task eaglefactions-S-1 owned by Plugin{id=eaglefactions, name=Eagle Factions, version=0.9.13, description=A factions plugin that will make managing your battle-server easier. :), authors=[Aquerr], source=/mods/EagleFactions-1.10.2-v0.9.13.jar}, but an error occured.
23.04 23:52:30 [Server] INFO java.lang.NullPointerException: null
23.04 23:52:30 [Server] INFO at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_151]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.logic.MainLogic.getPowerIncrement(MainLogic.java:40) ~[MainLogic.class:?]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.managers.PowerManager$1.accept(PowerManager.java:279) ~[PowerManager$1.class:?]
23.04 23:52:30 [Server] INFO at io.github.aquerr.eaglefactions.managers.PowerManager$1.accept(PowerManager.java:273) ~[PowerManager$1.class:?]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_151]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:278) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-3002]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
23.04 23:52:30 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
23.04 23:52:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
23.04 23:52:30 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
23.04 23:52:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Thank you for your time. I hope you got a fix for this :)

**Comment by Aquerr** [comment]
Something is happening with player’s power. 🤔

I will look at this today. 🙂

Could you please send me your Settings.conf file? For example, pasting Its content on pastebin.com and sending me a link.

**Comment by Aquerr** [comment]
@Bradman12312 Alright, let's get to work!

## Step One
In the log you provided, I noticed that you are using EagleFactions-**1.10.2** but your SpongeForge is for **1.12.2**. 😨 

So, the first thing you should do is changing your `EagleFactions.jar` file with [EagleFactions-1.12.2-v0.9.13](https://github.com/Aquerr/EagleFactions/releases/download/v0.9.13/EagleFactions-1.12.2-v0.9.13.jar)

## Step Two
The next thing you can try is deleting your `Settings.conf` file. If you have something in it that you would like to save (some configurations) then save this file somewhere and let the server generate a new file that contains a lot of new options and word/node changes. 

You can also look [here](https://github.com/Aquerr/EagleFactions/wiki/Configuration) to see how **today's Settings.conf file looks like**. 

Instead of genereting the new file by yourself, you can copy the content of `Settings.conf` from [here](https://github.com/Aquerr/EagleFactions/wiki/Configuration) and put it in your `Settings.conf` file. 🙂

## Step Three
Test it and tell me if there are any issues. I have tested `EagleFactions-1.12.2-v0.9.13` myself and It works fine so It shouldn't be different for others. 😜

**Comment by Bradman12312** [comment]
So far so good. i havent seen any issues yet. Thanks for the quick reply,
you're awesome :)

**Comment by Aquerr** [comment]
Good to here. 😄 You can close issue if everything looks fine. ;)
