### ISSUE TITLE
Commands Not Working

### ISSUE THREAD

**Issue by MoonCodeing** [Aquerr/EagleFactions#73]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2611-7.1.0-BETA-2983.jar

* **Plugin Version:** EagleFactions-1.12.2-v0.9.13.jar

## What happens?

The invite command doesn't work

## Expected result

It should work as /f invite <user>, and send them an invitation but it doesn't work

## More information

The only thing I can do is /f create, and /f admin, and /f flags, which are the only commands that work,
This is the error I get:

Error occured while executing command: net.minecraft.entity.player.EnittyPlayerMP cannot be cast to java.lang.Iterable

**Comment by Aquerr** [comment]
Copy and paste your server log file (with errors) on [Pastebin.com](https://pastebin.com/) and send me a link here. The error message you provieded is not sufficient.

**Comment by MoonCodeing** [comment]
https://pastebin.com/2p2EZMty

**Comment by MoonCodeing** [comment]
Another thing is that API-7+ is not the same as API-6 & lower

**Comment by Aquerr** [comment]
Yup, I know about it, and for API 7 users should use 1.12.2 version of Eagle Factions. And for API 6 - 1.11.2 version.

Strange thing that it is working so bad. 

There is a link to a (0.9.14-preview)[http://www.mediafire.com/file/fglmypd8dqly17i/EagleFactions-1.12.2-v0.9.14.jar] at SpongePowered Forums. I think that you could try this and tell me if it is working better.

**Comment by MoonCodeing** [comment]
In 0.19.14-preview admin mode is backwards. when you try and join a faction it won't let you in admin mode, if you turn it off it will.

**Comment by MoonCodeing** [comment]
could you notify me when the full release plugin is out?, as of beta doesn't work perfectly but at least you can claim, and still do things, also another thing is you can `/f sethome` in the safezone on the 0.13 version. so plz make it so you can only set `f home` in your own claim.
