### ISSUE TITLE
Entering safezone

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#8]
I have a suggestion for you !

Can you add an option for deny entering in safezone when player walking ? I think a possibility for modifying flags with /f flag or in config file :)

thank you :)

**Comment by Aquerr** [comment]
What do you mean by this?
Do you want to block entering to the SafeZone? And have an option for it in the config file?

**Comment by yodaa59** [comment]
Yes ! I do a pull request for that :)

All players go in safezone by using /spawn (for most players) or by using warps !

When he going in the warzone, i want to block him for going back and leave combat :)

**Comment by Aquerr** [comment]
Oh, ok, now I understand. Hmmm... I haven’t planned something like that but an option in the config file seems fine.

For me players should always be able to enter the SafeZone but it depends on what you want to accomplish.

I can add a node for this in the config file. Flags is not a thing I want to implement 😜

**Comment by yodaa59** [comment]
I updated my pull request because he have error, but you have just to add node in config file for using or not my pull request ! (i think the method i use it's good but i let you decide if it's ok for you :)

**Comment by Aquerr** [comment]
I will take a look at everything on friday. :)

**Comment by Aquerr** [comment]
Fixed!

I am closing this issue.

**Comment by yodaa59** [comment]
I don't know if it's possible to reopen an issue, but i have a little request on it :)

It's possible to block only when player walking ? because after tests, when player was dead, he respawn in the warzone where he was dead :(

Can you tell me if it's possible ?

**Comment by Aquerr** [comment]
I will take a look at this.

**Comment by Aquerr** [comment]
I have tested it now.

I can make a fix for this in the next version :)

Regards

**Comment by yodaa59** [comment]
Hello,

Have you had time to look for this fix?

Regards

**Comment by Aquerr** [comment]
Damn... I forgot about this... I have seen this problem but I just forgot about this...
I will fix this together with chat issue.

Regards

**Comment by Aquerr** [comment]
This should be fixed in 0.9.8 release.

I am closing this issue.
