### ISSUE TITLE
Followed commands dont work

### ISSUE THREAD

**Issue by YumaYamamoto** [Aquerr/EagleFactions#80]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar

* **Plugin Version:** EagleFactions-1.10.2-v0.9.16

## What happens?

Following commands dont work, just installed it and checked every command and this one dont work:

I gave admin every permission and users normal user permission, still not working.

/f top
/f coords
/f i
/f list
/f p

## Expected result

Just installed it.

## More information

One more question: How to check how much power a faction have.

**Comment by hampoelz** [comment]
You have installed the Sponge Version for Minecraft 1.12.2
But you use the EagleFactions version for Minecraft 1.10.2

Here you can download the right version of EagleFactions: https://github.com/Aquerr/EagleFactions/releases/download/v0.9.16/EagleFactions-1.12.2-v0.9.16.jar

**Comment by Aquerr** [comment]
I am closing this because of wrong issue description and I suppose it is working after trying version for 1.12.2
