### ISSUE TITLE
Bug with /f disband

### ISSUE THREAD

**Issue by Volgar18** [Aquerr/EagleFactions#81]
## Environment

* **Sponge Version:** <1.12.2-2705>

* **Plugin Version:** <2.15>

## What happens?

Hello, 

  I have a problem of duplication with Universe Guard 2. When a player fast break a protected block in protected region, the block don't break but loot so the player can have all blocks on the protected region. Sorry for my English, i'm french :)

Volgar18

**Comment by Volgar18** [comment]
Bad guithub

**Comment by Aquerr** [comment]
Hi!

I will see if I can fix this somehow.

Are you using the latest version of Eagle Factions?

W dniu pon., 13.08.2018 o 16:09 Volgar18 <notifications@github.com>
napisał(a):

**Comment by Volgar18** [comment]
Sorry, this issues is not for this plugin :D But i have a problem with you plugin so i enjoy. When a player disband faction nothing join a new faction, after reboot, old faction disband back!

Volgar18

**Comment by Volgar18** [comment]
Thank's. My issues is fixed with last version of eagle faction 0.10 :)

Thank's again

**Comment by Aquerr** [comment]
Good to hear! :)

Cheers!
