### ISSUE TITLE
duplication and missing events

### ISSUE THREAD

**Issue by RedCriterion** [Aquerr/EagleFactions#82]
## Environment

* **Sponge Version:** newest, api 7.1.0

* **Plugin Version:** newest

## What happens?
So recently i got sponge to add an event because flansmod weapons with explosive ammunition would use the "ExplosionEvent.Start" event which wasn't forwarded by sponge and thus would still detonate and destroy blocks under griefprevention the plugin. Here's some additional info to what aaron added in spongeforge build 3406: https://github.com/SpongePowered/SpongeForge/commit/c30e255f0b9c4b4a8615aa653f6689c51f49e0d8

I'm using eaglefactions and griefprevention on my server, since griefprevention can block any damage now, i only use it for spawnprotections. eaglefactions is much more user friendly.

Now the following regards i have when i tested eagle factions plugins. 
-The Detonation event is not cancelled which can lead to duplication with flansmod under certain circumstances
-The Forgeevent ExplosionEvent.Start is not supported as i can still blow (with flansmod explosive weapons) giant holes into claims protected with eagle factions.
-I know that the explosions of Industrial Craft 2 cause duplication eventually because they fire their own explosion events. In Flansmod's however it's not the mods fault. And i know this because in my spawn i can't duplicate items with it ( probably because all explosion is cancelled anyways).

I hope you can fix it and actually make your protections unbreakable :) 
thank you.

**Comment by Aquerr** [comment]
Hey!

If I remember correctly, Eagle Factions uses API 7.0.0. So that’s why not every event is handled.

I will see what I can do with this. :)

**Comment by RedCriterion** [comment]
Thank you! Do you have a discord server or anything where i can contact you directly? cause i'm also finding other problems with current protections that probably aren't hard to fix.

**Comment by Aquerr** [comment]
You can contact me here, at Spongepowered forum or at my Discord Server made specially for such things https://discord.gg/Zg3rWta
