### ISSUE TITLE
Error upon login [Bungee network]

### ISSUE THREAD

**Issue by Champion0912** [Aquerr/EagleFactions#83]
## Environment

* **Sponge Version:**  spongeforge-1.12.2-2705-7.1.0-BETA-3481

* **Plugin Version:** EagleFactions-1.12.2-v0.10.0

## What happens?

I join the network and do /server to join the factions server.
I log on to the server with no errors, until the second I seem to get in-game.
I then get this error in console: https://pastebin.com/RCKXrubW

## Expected result

No error message.

## More information

Command and plugin seems to work as intended.
Either way,  just wanted to report the error :-)

**Comment by Aquerr** [comment]
Ah, I know this bug. I have fixed it in in the dev version. Dev versions are available on my [Discord Server](https://discord.gg/Zg3rWta) but I will for sure make a new release this week that contains a fix for this. Thanks for making an issue though!

**Comment by Aquerr** [comment]
Closing because it it fixed in the latest version.
