### ISSUE TITLE
Could not pass ClientConnectionEvent$Join$Impl to Plugin eagle factions

### ISSUE THREAD

**Issue by sonic1crack** [Aquerr/EagleFactions#87]
## Environment

* **Sponge Version:** spongeforge-1.12.2-7.1.5

* **Plugin Version:** EagleFactions-1.12.2-v0.11.1

## What happens?

I am trying to configure a server with eagle factions. It seems like whenever I edit the config>eaglefactions>Settings.conf file and restart the server this error shows up ([Pastebin](https://pastebin.com/a3rrfdiq)) and the Settings.conf file code is deleted resulting in an empty file.

## More information

I am also using Luckperms and Nucleus pluggins if that helps. Thanks for the help.

**Comment by Aquerr** [comment]
Is the plugin working normally afterwards? Or are you not able to use it at all after this error?

**Comment by sonic1crack** [comment]
Works completely fine! I tried to add some items to the interact whitelist under safezone and here is where I got the issue. I won't be able to interact, like before changing it, but I can do /f home and everything. 

Thanks for the quick reply! :o

**Comment by Aquerr** [comment]
Shit, I know what the problem is. My bad. I will update it in the newest dev version. If you want to have it then check out my discord.

**Comment by sonic1crack** [comment]
You’re amazing! Thank you so much, I appreciate your hard work :)

**Comment by sonic1crack** [comment]
Update: I installed dev4 Eagle Factions version. Now there's is no such error in the server console but when launching the server it keeps emptiying my settings.conf file ONLY when I add items to 
`# Here you can specify which blocks players will be able to interact with. E.g. machines.
    interact-whitelist=[
        "enderio:windmill"
    ]`

**Comment by Aquerr** [comment]
Does the entire file disappear? Are you separating things with a comma “,”?

**Comment by sonic1crack** [comment]
I only placed one item so no coma needed. Disappears file content, not the file itslef, so I get an empty settings.conf file after restarting the server.

**Comment by Aquerr** [comment]
If you can recreate the problem then send me file content (for example on Discord) right before it gets deleted so that I can restart server myself and see this.

**Comment by sonic1crack** [comment]
I can give you full access to the server and its files if you want, I don't mind.

**Comment by Aquerr** [comment]
It is not needed. Just send me file’s content right before deletion and I will look at this tomorrow.

**Comment by sonic1crack** [comment]
I've sent it through pm on discord. Thanks for your time.

**Comment by sonic1crack** [comment]
> So, I looked at the problem with empty settings file. There is actually a very big error in the console. The settings file you sent to me had `minecraft:ender_chest` written in the interact-whitelist.
Server crashed because `minecraft:ender_chest` was not in between quotation marks `"minecraft:ender_chest"`."

Fixed! :D
