### ISSUE TITLE
Duplicating farm items in owned chunks you don't have access too

### ISSUE THREAD

**Issue by RyoshiKayo** [Aquerr/EagleFactions#88]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2768-7.1.5

* **Plugin Version:** EagleFactions-1.12.2-v0.11.1

## What happens?

When a user that is not in a faction, or not allied with a faction (AKA doesn't have perms to access blocks in claimed land), interacts with farmland you can spawn infinite amounts of items by right clicking on a crop.

## Expected result

User right clicks on an item and does NOT receive any items.

**Comment by Aquerr** [comment]
Damn, sounds like a serious problem and possible way for cheating... I don’t think I will have time for looking at this before Wednesday so this needs to wait but I will for sure prioritise this over other issues. You can of course go on my Discord Server (link on the forum or wiki) and check out latest DEV release which “may” solve this issue.

**Comment by Aquerr** [comment]
@RyoshiKayo So, I was looking at it and can't find anything wrong. I tested it both in safezone and in someone's faction's territory. I suppose it is fixed in the latest dev build.
I am thinking as well about right-clicking the farmland. You can't right-click a crop in normal minecraft to collect a crop right? or am I wrong?

**Comment by RyoshiKayo** [comment]
Right clicking crops is apart of extra utilities.

**Comment by Aquerr** [comment]
Maybe I configured something wrongly but I still cannot right click crops when I installed Extra Utilities. 🤔 Was looking in Extra Utilities's config file but I can't find anything related to "right-clicking". Any hints?
