### ISSUE TITLE
Faction chests not saving item metadata

### ISSUE THREAD

**Issue by RyoshiKayo** [Aquerr/EagleFactions#89]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2768-7.1.5
* **Plugin Version:** EagleFactions-1.12.2-v0.11.1

## What happens?

Place any item that has metadata associated with it in a faction chest, and it will either be reset or cleared. Damaged tools will have full health once taken out, enchanted books get their spells cleared (Still is called an enchanted book) etc.

## Expected result

Items keep their metadata values.

**Comment by Aquerr** [comment]
I mentioned in the 0.11.0 release that Chest Command is buggy and if someone likes taking risks then they can use it. I will of course work on it in the future and try to improve/fix it. Thanks for report. :)

**Comment by Aquerr** [comment]
Fixed in latest dev version. Future releases will contain this fix.
