### ISSUE TITLE
Syntaxe commands

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#9]
It is possible to add syntaxe when we type a sub command ?

Actually, when we type "/f c test" minecraft say not enought arguments but he don't say the syntaxe !

Cordially

**Comment by Aquerr** [comment]
Right now the only way to see which arguments you need to write is to use **/f help** command and search after the command you want to use.

I am planning to add something like you said too. Syntax/example/correct way of using a command will be shown for the player if it will type something wrong.

**Comment by Aquerr** [comment]
Added in the newest release 0.9.7.

I am closing this issue.
