### ISSUE TITLE
Bug with signs in SafeZone

### ISSUE THREAD

**Issue by MonstahGames** [Aquerr/EagleFactions#90]
## Environment

* **Sponge Version:** 1.12.2-2768-7.1.5

* **Plugin Version:** 4.3.75

## What happens?

When breaking a sign in the SafeZone, the sign doesn't break, but it's content (text) gets deleted.

## Expected result

The sign should keep it's text!

**Comment by Aquerr** [comment]
I am going to check this myself but I need to know few more things. Are you destroying a sign as a normal player (not op)? Are you in faction when you are doing it? Do you have faction’s admin mode on? Besides these questions... plugin version that you provided does not seem right. Latest release is 0.11.2.

**Comment by MonstahGames** [comment]
Woops, yeah, i accidentaly wrote the version of another plugin. I'm on 0.11.1, (will update soon)
I'm using LuckPerms, i am not op and have demoted myself to the normal player role.
Players have the `eaglefactions.player.*` permission.
I have just checked it again (this time not in a faction and making sure admin mode was off)

When i break a sign, it doesn't go away, but the content (text) on it does.

**Comment by Aquerr** [comment]
Alright, noted. I will fix this asap. 😄

**Comment by Aquerr** [comment]
@MonstahGames I tried it myself in the latest build and it is working fine. Check if it fixes it for you. [EagleFactions-1.12.2-v.0.11.2_34](http://bartlomiejstepien.pl:8080/job/EagleFactions/lastSuccessfulBuild/artifact/build/libs/EagleFactions-1.12.2-v0.11.2_34.jar)

**Comment by MonstahGames** [comment]
To download the jar, i need to be logged in. Is there any other way of getting the jar?

**Comment by Aquerr** [comment]
@MonstahGames Ah, sorry, my bad. Try again the same link. :)

**Comment by MonstahGames** [comment]
Still having the same problem on 0.11.2. I attached a video with whats happening exactly.
https://www.youtube.com/watch?v=S4xIR1oJzXI&feature=youtu.be
I wonder if this may be another plugin or mod causing this, but i'm guessing not

**Comment by MonstahGames** [comment]
Ok, so it seems that when i relog, the signs get their text back. Could this be something client side?

**Comment by Aquerr** [comment]
Well, I am sure text is not actually disappearing. The thing you showed on the video does not happen for me. Text stays on the sign after breaking.

It looks like the server is not sending the information to the client fast enough and client thinks that sign has actually been destroyed. I am afraid I can't do more about it.

**Comment by MonstahGames** [comment]
Yep, i'll have to do some more research on my end. Thanks!
