### ISSUE TITLE
Faction & Player power config

### ISSUE THREAD

**Issue by sumaso** [Aquerr/EagleFactions#93]
## Environment

* **Sponge Version:** SpongeForge 1.12.2-2768-7.1.6-RC3686

* **Plugin Version:** EagleFactions-1.12.2-v0.12.0.jar

## What happens?

These are my power settings, I'm trying to change them to such high values because my friends and I are tyring to create a "nation-based" economy-war faction pvp server.
}
power {
    # How much power will be removed on player death. Default: 2
    decrement=100
    # How much power will be restored for player after 1 minute of playing. (0.04 per minute = 1,2 per hour.) Default: 0.04
    increment=4
    # Player kill award. Default: 1
    kill-award=100
    # Maximum amount of power a player can have. Default: 10
    max-power=1000
    # Penalty after killing a teammate. Default: 1
    penalty=100
    # Starting amount of power. Default: 5
    start-power=500

## Expected result

The amounts of power should be increased as specified, but they would not work. Server testing revealed that the defaults prevail and I can't find a reason

## More information

I have saved, reinstalled, looked for conflicts. Nothing works. Please help!! thanks

**Comment by Aquerr** [comment]
Hello! Thank you for creating an issue. I will investigate it as soon as possible.

**Comment by Aquerr** [comment]
Closing because it is working fine but all old players must be removed after changing these settings (so that they can get new max-power value etc.).
