### ISSUE TITLE
A player can't hurt himself with an arrow.

### ISSUE THREAD

**Issue by HeroBrine1st** [Aquerr/EagleFactions#94]
## Environment

* **Sponge Version:** 1.12.2-7.1.7-SNAPSHOT

* **Plugin Version:** 0.12.0

I can explain why there is an error, so this text I write is not quite on the template.

## What happens?

The player can't hurt himself with an arrow.

The problem is here:
https://github.com/Aquerr/EagleFactions/blob/1.12.2/api-7.0.0/src/main/java/io/github/aquerr/eaglefactions/listeners/EntityDamageListener.java#L187

When a player attacks by himself with an arrow, the following happens:

1. It is checked whether the players are in the same faction.
This condition is fulfilled because the same player has the same faction.
2. Check whether the friendlyfire is enabled in the plugin configuration. In my case, it is off - the check does not pass.
In this case, the action is canceled and no damage is done.
3. The desired action is not performed.

Why do players need it:

Exists a technique of long-range flights on Elytra.
It requires a bow with Punch II and an elytra with Unbreacking III (everything else is optional and only required to reduce damage) and allows you to fly incredibly far by getting your own arrow into yourself, speeding up the player due to Punch II.

The plugin does not allow this until friendlyfire is disabled.

**Comment by Aquerr** [comment]
Thanks for reporting the issue! I will try to fix it today.

**Comment by Aquerr** [comment]
@HeroBrine1st The problem should be fixed now in the latest dev release. Here is the link [EagleFactions-Build-91](https://cdn.discordapp.com/attachments/553855702792273922/592745483055923224/EagleFactions-1.12.2-v0.12.0_91.jar) if you want to download it. If link does not work then try [this one](https://jenkins.bartlomiejstepien.pl/job/EagleFactions-dev-build/91/artifact/build/libs/EagleFactions-1.12.2-v0.12.0_91.jar). Don't know when "normal" release will arrive but hopefully this summer.
