### ISSUE TITLE
Crashes upon entering the nether

### ISSUE THREAD

**Issue by FiveSquared25** [Aquerr/EagleFactions#98]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2838-7.1.7-RC3830

* **Plugin Version:** 0.12.0

## What happens?

When a user attempts to enter the nether, it causes a server crash. This is also the case when an item is thrown through the portal, or a pigman comes through from the nether side of the portal. We aren't 100% sure this is a factions related problem, but the server loads perfectly with the standard modpack (tekxit 3)

## Expected result

We'd like to be able to go to nether

## More information

Crash report available here or attached https://pastebin.com/DeQ1LDWQ
[crash-2019-09-15_10.23.46-server.txt](https://github.com/Aquerr/EagleFactions/files/3613299/crash-2019-09-15_10.23.46-server.txt)

**Comment by Aquerr** [comment]
Have you tried it without Eagle Factions but with SpongeForge only?

**Comment by FiveSquared25** [comment]
I considered doing that, but I'm worried that if I do that we lose the past 20 odd days that we've been creating our factions. If we could remove it without any progress loss I'll do it right away, but I'm fairly new to modding Minecraft and the like so I haven't been rushing into anything

**Comment by Aquerr** [comment]
If you just remove **eaglefactions.jar** from your mods folder then all factions data will be still available in **config/eaglefactions**. Server should not remove that folder after you removing the jar.

But you can always make a copy of your **config/eaglefactions** folder. Just in case.

Then you will be able to test the server only with Sponge. 
After testing, just put **eaglefactions.jar** back into the **mods** folder and factions will work like before. :)

**Comment by FiveSquared25** [comment]
Yep, I gave it a test without eaglefactions and it still crashed, so I tested without sponge and it worked, so I'm going to jump straight in and say its a sponge problem and not a factions problem. Thanks for the help
